version: "3.7"

services:
  etcd:
    image: bitnami/etcd:latest
    restart: unless-stopped
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    networks:
      - internal

  pkg:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/go/src/github.com/alexeyco/leader
    working_dir: /go/src/github.com/alexeyco/leader
    command: tail -f /dev/null

networks:
  internal:
    external: false
